/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package database;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

public class StatistikaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatistikaForma.class.getName());

    
    public void ucitajStatistiku() {

    try {

        DefaultTableModel model =
                (DefaultTableModel) tblStatistika.getModel();

        model.setRowCount(0);

        Connection con = DBConnection.connect();

        Statement st = con.createStatement();

       ResultSet rs = st.executeQuery(
    "SELECT p.Predmet, " +
    "SUM(CASE WHEN i.GodinaSlusanja=2024 THEN 1 ELSE 0 END) AS G2024, " +
    "SUM(CASE WHEN i.GodinaSlusanja=2025 THEN 1 ELSE 0 END) AS G2025, " +
    "SUM(CASE WHEN i.GodinaSlusanja=2026 THEN 1 ELSE 0 END) AS G2026 " +
    "FROM Predmet p " +
    "JOIN IzabraniPredmet i ON p.PredmetID=i.PredmetID " +
    "GROUP BY p.Predmet"
);

        while(rs.next()) {

            model.addRow(new Object[]{

                rs.getString("Predmet"),
                rs.getInt("G2024"),
                rs.getInt("G2025"),
                rs.getInt("G2026")
            });
        }

    } catch(Exception e) {

        e.printStackTrace();
    }
}
    
public void nacrtajGraf() {

    try {

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        Connection con = DBConnection.connect();
        Statement st = con.createStatement();

        String sql =
        "SELECT p.Predmet, " +
        "SUM(CASE WHEN i.GodinaSlusanja=2024 THEN 1 ELSE 0 END) AS G2024, " +
        "SUM(CASE WHEN i.GodinaSlusanja=2025 THEN 1 ELSE 0 END) AS G2025, " +
        "SUM(CASE WHEN i.GodinaSlusanja=2026 THEN 1 ELSE 0 END) AS G2026 " +
        "FROM Predmet p " +
        "JOIN IzabraniPredmet i ON p.PredmetID=i.PredmetID ";

        // FILTER (ISTO KAO ZA TABELO)
        String where = "";

        if(chkMatematika.isSelected()) {
            where += "p.Predmet='Matematika I' OR ";
        }

        if(chkWeb.isSelected()) {
            where += "p.Predmet='Web Programiranje' OR ";
        }

        if(jCheckBox1.isSelected()) {
            where += "p.Predmet='Baze Podataka' OR ";
        }

        if(jCheckBox3.isSelected()) {
            where += "p.Predmet='Racunarske Mreze' OR ";
        }

        if(jCheckBox2.isSelected()) {
            where += "p.Predmet='Programiranje' OR ";
        }

        if(!where.isEmpty()) {
            where = "WHERE " + where.substring(0, where.length() - 4);
            sql += where;
        }

        sql += " GROUP BY p.Predmet";

        ResultSet rs = st.executeQuery(sql);

        while(rs.next()) {

            String predmet = rs.getString("Predmet");

            dataset.addValue(rs.getInt("G2024"), predmet, "2024");
            dataset.addValue(rs.getInt("G2025"), predmet, "2025");
            dataset.addValue(rs.getInt("G2026"), predmet, "2026");
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Statistika predmeta",
                "Godina",
                "Broj studenata",
                dataset
        );

        ChartPanel panel = new ChartPanel(chart);

        jPanelGraf.removeAll();
        jPanelGraf.setLayout(new java.awt.BorderLayout());
        jPanelGraf.add(panel);
        jPanelGraf.validate();

    } catch(Exception e) {
        e.printStackTrace();
    }
}
    
    public StatistikaForma() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatistika = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        chkMatematika = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        chkWeb = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanelGraf = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblStatistika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Predmet", "2024", "2025", "2026"
            }
        ));
        jScrollPane1.setViewportView(tblStatistika);

        jButton1.setText("Prikazi");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        chkMatematika.setText("Matematika I");

        jCheckBox2.setText("Programiranje");

        chkWeb.setText("Web Programiranje");
        chkWeb.addActionListener(this::chkWebActionPerformed);

        jCheckBox1.setText("Baza Podataka");

        jCheckBox3.setText("Racunarske Mreze");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkMatematika)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox3)
                    .addComponent(chkWeb)
                    .addComponent(jCheckBox2))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(chkMatematika)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkWeb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanelGrafLayout = new javax.swing.GroupLayout(jPanelGraf);
        jPanelGraf.setLayout(jPanelGrafLayout);
        jPanelGrafLayout.setHorizontalGroup(
            jPanelGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        jPanelGrafLayout.setVerticalGroup(
            jPanelGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setText("Izadji");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ucitajStatistiku();
                                       
 try {

        DefaultTableModel model =
                (DefaultTableModel) tblStatistika.getModel();

        model.setRowCount(0);

        Connection con = DBConnection.connect();
        Statement st = con.createStatement();

        String sql =
        "SELECT p.Predmet, " +
        "SUM(CASE WHEN i.GodinaSlusanja=2024 THEN 1 ELSE 0 END) AS G2024, " +
        "SUM(CASE WHEN i.GodinaSlusanja=2025 THEN 1 ELSE 0 END) AS G2025, " +
        "SUM(CASE WHEN i.GodinaSlusanja=2026 THEN 1 ELSE 0 END) AS G2026 " +
        "FROM Predmet p " +
        "JOIN IzabraniPredmet i ON p.PredmetID=i.PredmetID ";

        // FILTER
        String where = "";

        if(chkMatematika.isSelected()) {
            where += "p.Predmet='Matematika I' OR ";
        }

        if(chkWeb.isSelected()) {
            where += "p.Predmet='Web Programiranje' OR ";
        }

        if(jCheckBox1.isSelected()) {
            where += "p.Predmet='Baze Podataka' OR ";
        }

        if(jCheckBox3.isSelected()) {
            where += "p.Predmet='Racunarske Mreze' OR ";
        }

        if(jCheckBox2.isSelected()) {
            where += "p.Predmet='Programiranje' OR ";
        }

        if(!where.isEmpty()) {
            where = "WHERE " + where.substring(0, where.length() - 4);
            sql += where;
        }

        sql += " GROUP BY p.Predmet";

        ResultSet rs = st.executeQuery(sql);

        while(rs.next()) {

            model.addRow(new Object[]{
                rs.getString("Predmet"),
                rs.getInt("G2024"),
                rs.getInt("G2025"),
                rs.getInt("G2026")
            });
        }
        nacrtajGraf();

    } catch(Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWebActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             GlavnaForma p = new GlavnaForma();
p.setVisible(true);

this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StatistikaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkMatematika;
    private javax.swing.JCheckBox chkWeb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGraf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblStatistika;
    // End of variables declaration//GEN-END:variables
}

